"use client";

import Link from "next/link";

export default function LearnMorePage() {
  return (
    <div
      style={{
        minHeight: "100vh",
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
        background: "linear-gradient(180deg, #ffe7c7 0%, #ffffff 100%)",
        padding: "40px 20px",
        fontFamily: "Segoe UI, Roboto, sans-serif",
      }}
    >
      <div
        style={{
          backgroundColor: "white",
          borderRadius: "16px",
          boxShadow: "0 4px 12px rgba(0,0,0,0.1)",
          maxWidth: "800px",
          width: "100%",
          padding: "60px 60px",
          border: "1px solid #ffd79b",
          color: "#222", // ✅ makes sure text is visible
        }}
      >
        <h1
          style={{
            textAlign: "center",
            fontSize: "2.4rem",
            fontWeight: "800",
            color: "#1976d2",
            marginBottom: "10px",
          }}
        >
          TheTestifyAI
        </h1>

        <h2
          style={{
            textAlign: "center",
            fontSize: "1.6rem",
            fontWeight: "700",
            color: "#ff9800",
            marginBottom: "40px",
          }}
        >
          Learn More
        </h2>

        <div
          style={{
            fontSize: "1.05rem",
            color: "#333", // ✅ ensures dark readable text
            lineHeight: "1.7",
            textAlign: "justify",
          }}
        >
          <p style={{ marginBottom: "20px" }}>
            <strong>TheTestifyAI</strong> is built to make learning smarter and
            easier on any device — phone, tablet, or computer. You can take
            tests on anything you choose, with adjustable difficulty and
            question count.
          </p>

          <p style={{ marginBottom: "20px" }}>
            Every test is generated by AI that studies your topic and writes
            high-quality multiple-choice questions. After each question, you’ll
            see an explanation to help you understand why the right answer is
            correct.
          </p>

          <p style={{ marginBottom: "20px" }}>
            Because all content is AI-generated, there might be small
            inaccuracies. If you find any issues or want to share feedback,
            please email us at:
          </p>

          <p
            style={{
              color: "#1976d2",
              fontWeight: "600",
              textAlign: "center",
            }}
          >
            thetestifyai@gmail.com
          </p>

          <p
            style={{
              textAlign: "center",
              marginTop: "40px",
              color: "#777",
              fontStyle: "italic",
            }}
          >
            More updates coming soon — stay tuned for exciting new features!
          </p>
        </div>

        <div style={{ textAlign: "center", marginTop: "50px" }}>
          <Link
            href="/"
            style={{
              backgroundColor: "#1976d2",
              color: "white",
              padding: "12px 30px",
              borderRadius: "10px",
              fontWeight: "700",
              fontSize: "1.1rem",
              textDecoration: "none",
            }}
          >
            Home
          </Link>
        </div>
      </div>
    </div>
  );
}
