"use client";

import Link from "next/link";

export default function LearnMorePage() {
  return (
    <div
      style={{
        minHeight: "100vh",
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
        background: "linear-gradient(180deg, #fffaf5 0%, #ffffff 100%)",
        padding: "40px 20px",
        color: "#333",
        fontFamily: "Segoe UI, Roboto, sans-serif",
      }}
    >
      <div
        style={{
          backgroundColor: "white",
          borderRadius: "24px",
          boxShadow: "0 6px 20px rgba(0,0,0,0.05)",
          border: "2px solid #ffb74d",
          maxWidth: "800px",
          padding: "50px",
          textAlign: "center",
        }}
      >
        <h1
          style={{
            fontSize: "2.5rem",
            fontWeight: "800",
            color: "#1976d2",
            marginBottom: "10px",
          }}
        >
          TheTestifyAI
        </h1>

        <h2
          style={{
            fontSize: "1.6rem",
            fontWeight: "700",
            color: "#1976d2",
            marginBottom: "30px",
          }}
        >
          Learn More
        </h2>

        <div
          style={{
            textAlign: "justify",
            fontSize: "1.05rem",
            lineHeight: "1.7",
            color: "#444",
            marginBottom: "40px",
          }}
        >
          <p style={{ marginBottom: "20px" }}>
            <strong>TheTestifyAI</strong> is a learning tool built for phones,
            tablets, and computers. You can take tests on any topic you want,
            while adjusting both the difficulty and number of questions to your
            liking.
          </p>
          <p style={{ marginBottom: "20px" }}>
            Each test is generated by AI — it studies your topic, creates
            accurate multiple-choice questions, and provides four answer options
            (one correct). After answering, you'll see a short explanation to
            help you understand the reasoning behind it.
          </p>
          <p style={{ marginBottom: "20px" }}>
            Because the content is AI-generated, there may sometimes be small
            errors. If you find one or just want to share feedback, contact us
            at:
          </p>
          <p
            style={{
              color: "#1976d2",
              fontWeight: "600",
              textAlign: "center",
            }}
          >
            thetestifyai@gmail.com
          </p>
        </div>

        <Link
          href="/"
          style={{
            backgroundColor: "#1976d2",
            color: "white",
            padding: "12px 30px",
            borderRadius: "12px",
            fontWeight: "700",
            fontSize: "1.1rem",
            textDecoration: "none",
            transition: "background-color 0.2s ease",
          }}
        >
          Home
        </Link>

        <p
          style={{
            marginTop: "40px",
            fontSize: "0.95rem",
            color: "#888",
            fontStyle: "italic",
          }}
        >
          More updates coming soon — stay tuned for new features and learning
          tools.
        </p>
      </div>
    </div>
  );
}
