"use client";

import Link from "next/link";

export default function LearnMorePage() {
  return (
    <div className="min-h-screen flex flex-col items-center justify-center bg-white text-center text-gray-900 p-6">
      <h1 className="text-4xl font-bold text-blue-700 mb-3">TestifyAI</h1>
      <h2 className="text-2xl font-semibold text-blue-600 mb-6">Learn More</h2>

      <div className="max-w-2xl text-gray-700 leading-relaxed mb-8">
        <p className="mb-4">
          TestifyAI is a website suitable for phones, computers, and tablets.
          This app lets you take a test on anything you want and allows you to
          choose both the difficulty and the number of questions.
        </p>
        <p className="mb-4">
          The information for each test is processed by an AI, which searches
          for the topic, learns about it, and then creates a question with four
          possible answers—only one of which is correct. After each question,
          you can view the explanation of the correct answer.
        </p>
        <p className="mb-4">
          Because the content is generated by AI, there may occasionally be
          mistakes in the questions or answers. If you notice any issues or
          have feedback, please contact us at:
        </p>
        <p className="font-semibold text-blue-700">thetestifyai@gmail.com</p>
      </div>

      <Link
        href="/"
        className="bg-blue-600 hover:bg-blue-700 text-white font-semibold py-3 px-8 rounded-xl transition text-lg"
      >
        Home
      </Link>
    </div>
  );
}
